- name: 'install required packages'
  apt:
    pkg:
      - 'nginx'
      - 'certbot'
      - 'python3-certbot-nginx'
      - 'cron'
    state: 'present'
- name: 'allow incoming HTTP(S) traffic'
  community.general.ufw:
    rule: 'allow'
    name: 'Nginx Full'
- name: 'get certificate for the first time'
  command: 'certbot -n --nginx certonly -d {{ hostname }} --agree-tos --email {{ letsencrypt_email }}'
  args:
    creates: '/etc/letsencrypt/live/{{ hostname }}'
- name: 'remove default nginx site'
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: 'absent'
- name: 'add nginx configuration'
  template:
    src: 'hostname.conf'
    dest: '/etc/nginx/sites-enabled/{{ hostname }}.conf'
- name: 'reload nginx'
  systemd_service:
    name: 'nginx'
    state: 'reloaded'
    enabled: true
- name: 'setup cronjob for certificate renewal'
  cron:
    name: 'certbot-renewal'
    job: "/bin/bash -lc 'certbot -q renew'"
    minute: '0'
    hour: '0'