# The ID of the GitHub app associated to the deployment
github_app_id: 99999

# The private key of the GitHub app associated to the deployment
github_app_key: |-
  -----BEGIN RSA PRIVATE KEY-----
  <SECRET BASE64 GOES HERE>
  -----END RSA PRIVATE KEY-----

# The secret that GitHub will use to sign webhook events
webhook_secret: 'very secret string'

# The DSN used to log traces to Sentry
sentry_dsn: 'https://examplePublicKey@o0.ingest.sentry.io/0'

# The email address used for the Let's Encrypt ACME account
letsencrypt_email: 'example@example.com'

# Configuration for Bencher.dev (optional, remove if unused)
bencher:
  # The API token for Bencher.dev
  api_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

  # The Bencher Project ID
  project_id: 'rustls-821705769'

  # The Bencher Testbed ID
  testbed_id: 'bare-metal-server'
