---
# Ensure the CPUs are always operating at the maximum frequency
- name: Upload scaling governor script
  ansible.builtin.copy:
    src: set-scaling-governor.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
- name: Upload systemd service file
  ansible.builtin.copy:
    src: set-scaling-governor.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Enable systemd service
  ansible.builtin.systemd_service:
    name: set-scaling-governor
    state: started
    enabled: true
    daemon_reload: true
