name: ansible-lint

on:
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        run: nix develop --command bash -c "cd ansible && ansible-lint"